export const gEmail = [
  {
    id: "e101",
    subject: "We just added a TV show you might like.",
    body: "You\n Joe Goldberg  is back -- or was he always right behind you this whole time? -- for the third season of Netflix's creepy stalker drama, except this time he may not be the one to go to extreme lengths to get what he wants. Now in California and married (!!) to Love (Victoria Pedretti), Joe is raising his son in a chill suburb and everything is going great. OK, not really, because Joe's gotta Joe and he develops an unhealthy obsession with his new neighbor. But will Love let him do his thing? ",
    isRead: false,
    sentAt: 1636133342918,
    from: "netflix@mailer.netflix.com",
    isStared : false,
    to: "team2@eamil.com",
  },
  {
    id: "e102",
    subject: "Your profile is looking great",
    body: `Your profile is looking great\n
    Your work and accomplishments are being recognized\n
    text.link('https://www.linkedin.com/')`,
    isRead: false,
    sentAt: 1636233342918,
    from: "linkedin@linkedin.com",
    isStared : true,
    to: "team2@eamil.com",
  },
  {
    id: "e103",
    subject: "My experience",
    body: `Hey Joe,
    Well, dig I'm goin' way down south
    Way down to Mexico way Alright\n
    I'm goin' way down south\n
    Way down where I can be free\n
    Ain't no one gonna find me\n
    Ain't no hangman gonna\n
    He ain't gonna put a rope around me\n
    You better believe right now\n
    I gotta go now`,
    isRead: false,
    sentAt: 1636333342918,
    from: "JH-Experience@rock.com",
    isStared : true,
    to: "team2@eamil.com",
  },
  {
    id: "e104",
    subject: "15% Discount on flexible orders",
    body: `It's time for vacation\n
    Enjoy the end of 2021 with discounts of 15% and up\n
    Valid for stays with check-out date before 4 January 2022\n	
    You will save even more, if you combine this promotion with Genius benefits.\n
    text.link('https://www.booking.com')
    `,
    isRead: false,
    sentAt: 1636433342918,
    from: "momo@momo.com",
    isStared : true,
    to: "team2@eamil.com",
  },
  {
    id: "e105",
    subject: "Ebay",
    body: ``,
    isRead: false,
    sentAt: 1636533342918,
    from: "booking@sg.booking.com",
    isStared : true,
    to: "team2@eamil.com",
  },
  {
    id: "e106",
    subject: "Ebay",
    body: ``,
    isRead: false,
    sentAt: 1636633342918,
    from: "momo@momo.com",
    isStared : true,
    to: "team2@eamil.com",
  },
  {
    id: "e107",
    subject: "Ebay",
    body: ``,
    isRead: false,
    sentAt: 1636733342918,
    from: "momo@momo.com",
    isStared : true,
    to: "team2@eamil.com",
  },
  {
    id: "e108",
    subject: "Ebay",
    body: ``,
    isRead: false,
    sentAt: 1636833342918,
    from: "momo@momo.com",
    isStared : false,
    to: "team2@eamil.com",
  },
  {
    id: "e109",
    subject: "Ebay",
    body: ``,
    isRead: false,
    sentAt: 1636933342918,
    from: "momo@momo.com",
    isStared : false,
    to: "team2@eamil.com",
  },
  {
    id: "e110",
    subject: "Ebay",
    body: ``,
    isRead: false,
    sentAt: 1636093342918,
    from: "momo@momo.com",
    isStared : false,
    to: "team2@eamil.com",
  },
  {
    id: "e111",
    subject: "Ebay",
    body: ``,
    isRead: false,
    sentAt: 1636533342918,
    from: "momo@momo.com",
    isStared : false,
    to: "team2@eamil.com",
  },
  {
    id: "e112",
    subject: "Ebay",
    body: ``,
    isRead: false,
    sentAt: 1636533342918,
    from: "momo@momo.com",
    isStared : false,
    to: "team2@eamil.com",
  },
  {
    id: "e113",
    subject: "Ebay",
    body: ``,
    isRead: false,
    sentAt: 1636533342918,
    from: "momo@momo.com",
    isStared : false,
    to: "team2@eamil.com",
  },
  {
    id: "e114",
    subject: "Ebay",
    body: ``,
    isRead: false,
    sentAt: 1636533342918,
    from: "momo@momo.com",
    isStared : false,
    to: "team2@eamil.com",
  },
  {
    id: "e115",
    subject: "Ebay",
    body: ``,
    isRead: false,
    sentAt: 1636533342918,
    from: "momo@momo.com",
    isStared : false,
    to: "team2@eamil.com",
  },
  {
    id: "e116",
    subject: "Miss you!",
    body: "Would love to catch up sometimes",
    isRead: true,
    sentAt: 1636433342918,
    from: "bobo@bobo.com",
    isStared : false,
    to: "team2@eamil.com",
  },
  {
    id: "e117",
    subject: "NO more",
    body: "NO more NO more",
    isRead: true,
    sentAt: 1636333342918,
    from: "nono@nono.com",
    isStared : false,
    to: "team2@eamil.com",
  },
  {
    id: "e118",
    subject: "MIMI!",
    body: "Would love to catch up sometimes",
    isRead: false,
    sentAt: 1636233342918,
    from: "mimi@mimi.com",
    isStared : false,
    to: "team2@eamil.com",
  },
  {
    id: "e119",
    subject: "sent",
    body: "sent sent sent",
    isRead: true,
    sentAt: 1551136930594,
    from: "team2@email.com",
    isStared : false,
    to: "team2@eamil.com",
  },
];
