export const gEmail = [
  {
    id: "e101",
    subject: "Ebay",
    body: "bay bay bay",
    isRead: false,
    sentAt: 1551133930594,
    from: "momo@momo.com",
    to: "coding@academy.com",
  },
  {
    id: "e102",
    subject: "Miss you!",
    body: "Would love to catch up sometimes",
    isRead: true,
    sentAt: 1551134930594,
    from: "bobo@bobo.com",
    to: "coding@academy.com",
  },
  {
    id: "e103",
    subject: "NO more",
    body: "NO more NO more",
    isRead: true,
    sentAt: 1551135930594,
    from: "nono@nono.com",
    to: "coding@academy.com",
  },
  {
    id: "e104",
    subject: "MIMI!",
    body: "Would love to catch up sometimes",
    isRead: false,
    sentAt: 1551136930594,
    from: "mimi@mimi.com",
    to: "coding@academy.com",
  },
];
